export HOMEBASE_BASHRC="$(readlink -f "${BASH_SOURCE[0]}")"
export HOMEBASE_BASHLIB="$(dirname "$HOMEBASE_BASHRC")"

source "$HOMEBASE_BASHLIB/startx-hook.sh"
source "$HOMEBASE_BASHLIB/without-startx.sh"
