tty | grep -E '^/dev/tty[2-9]' && exec startx

set -o vi

export PS1='\n\n  \033[35m---{ \033[33m\$?=$? \033[35m; \033[33m\u \033[35m@ \033[33m\h \033[35m: \033[33m\w \033[35m}---\033[0m\n\$ '

export PATH="$HOME/.nix-profile/bin"
export EDITOR='vim'
