#! /usr/bin/env bash
set -fuxo pipefail

exec > ~/.cache/leftwm-homebase.up.log 2>&1

xss-lock --transfer-sleep-lock \
	i3lock --nofork -c "${HOMEBASE_USER_COLOR:-554466}" &

unclutter -idle 1 &
xsetroot -solid '#555588'
polybar &
dunst &
alacritty --command zellij-dir-session "$HOME" &
