#! /usr/bin/env bash

UPSTREAM='{{git_clone_canonical}}/bin/git-clone-canonical'
SET_SYMLINK='{{set_symlink}}/bin/set-symlink'

function main
{
  if [ $# -eq 1 ] && [ "$1" = '--update-hack-links' ]
  then
    update-hack-links
  else
    delegate-upstream "$@"
  fi
}

function delegate-upstream
{
  eval "${UPSTREAM}" "$@" && eval "$0" --update-hack-links
}

function update-hack-links
{
  failures=0

  cd ~/hack

  for repo in $(find ~/src -type d -name .git | xargs dirname)
  do
    reponame="$(basename "$repo")"
    slug="$(basename "$(dirname "$repo")")"
    set-symlink "${repo}" "./${reponame}.${slug}" || failures=$(( "$failures" + 1 ))
    # Make a shorthand link if one does not exist:
    [ -L "./${reponame}" ] || set-symlink "./${reponame}.${slug}" "./${reponame}"
  done

  exit "$failures"
}

function set-symlink
{
  eval "$SET_SYMLINK" "$@"
}

source '{{bash_postlude}}/lib/postlude.bash'
