[user]
name = 'nejucomo'
email = 'nobody@nowhere.org'
username = 'nejucomo'

[templates]
new_description = '''
if(parents.len() > 1,
  "Merge " ++ parents.skip(1).map(|p| if(
    p.bookmarks(),
    p.bookmarks().first().name(),
    p.change_id().shortest(8)
  )).join(", ") ++ " into " ++ if(
    parents.first().bookmarks(),
    parents.first().bookmarks().first().name(),
    parents.first().change_id().shortest(8)
  ) ++ "\n",
  ""
)
'''
