#! /usr/bin/env bash

set -efuxo pipefail

depgraph='{{cargo_depgraph}}/bin/cargo-depgraph'
dot='{{graphviz}}/bin/dot'

if [ "$*" = '--help' ]
then
  eval "$depgraph" depgraph --help
else
  eval "$depgraph" depgraph "$@" \
    | "$dot" -Tsvg \
    > target/depgraph.svg
fi

