#! {{bash}}/bin/bash

function main
{
  parse-args 'src' "$@"

  SRCGIT="${src}/.git"

  local retcode=0

  for remote in $(src-git remote)
  do
    if ! log-run git remote add "$remote" "$(src-git remote get-url "$remote")"
    then
      retcode=1
    fi
  done

  return "$retcode"
}

function src-git
{
  git --git-dir "$SRCGIT" "$@"
}

source '{{bash_postlude}}/lib/postlude.bash'
