#! /usr/bin/env bash
set -fuxo pipefail

exec > ~/.cache/leftwm-homebase.up.log 2>&1

function launch
{
  cmd="$1"
  "$@" 2>&1 \
		| sed "s/^/${cmd}: /" \
		|| notify-send --app-name 'leftwm-theme-up' "$cmd" 'failed' \
		&
}

launch xss-lock --transfer-sleep-lock \
	-- i3lock --nofork -c "${HOMEBASE_USER_COLOR:-554466}"

launch unclutter -idle 1
xsetroot -solid '#550088'
launch polybar
launch dunst
