#! /usr/bin/env bash
set -fuxo pipefail

exec > ~/.cache/leftwm-theme-homebase.up.log 2>&1

function launch
{
  cmd="$1"
  "$@" 2>&1 \
		| sed "s/^/${cmd}: /" \
		|| notify-send --app-name 'leftwm-theme-up' "$cmd" 'failed' \
		&
}

export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

leftwm command "LoadTheme $SCRIPTPATH/theme.ron"

launch xss-lock --transfer-sleep-lock \
	-- i3lock --nofork -c "${HOMEBASE_USER_COLOR:-554466}"

launch unclutter -idle 1
xsetroot -solid '#550088'
launch polybar
launch dunst
